Use GitHub Actions workflow to build Docker images

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,137 +1,175 @@
 name: Build and test
+
 on:
-  pull_request:
-  workflow_dispatch:
+  push:
+    branches:
+      - main
+      - thumbor-7
+
 permissions:
   contents: read
+  packages: write
+
 jobs:
-  thumbor:
+  build:
+    name: Build and test Docker images
+
     runs-on: ubuntu-latest
+
+    env:
+      #PLATFORM=linux/amd64,linux/arm64
+      PLATFORM: linux/amd64
+
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      - name: get thumbor version
+      - uses: docker/setup-qemu-action@v2
+
+      # This enables native caching from Docker into the GHA cache system:
+      - uses: crazy-max/ghaction-github-runtime@v2
+
+      - uses: actions/checkout@v3
+
+      - name: Find version of Thumbor used
         id: thumbor
         run: |
-          echo "VERSION=$(cat thumbor/requirements.txt| grep thumbor== | cut -d= -f 3)" >> $GITHUB_OUTPUT
-      - name: build image
-        ## TODO set platform to linux/amd64,linux/arm64 once supported
+          VERSION=$(cat thumbor/thumbor/requirements.txt| grep thumbor== | cut -d= -f 3)
+          if [[ -z "$VERSION" ]]; then
+            echo "Failed to find version of Thumbor used"
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
+
+      - run: docker buildx create --use --driver=docker-container
+
+      - name: Build Thumbor base image
         run: |
-          docker buildx build --platform "linux/amd64" \
-          -o type=docker,dest=/tmp/thumbor.tar \
-          -f thumbor/Dockerfile \
-          --tag minimalcompact/thumbor:${{ steps.thumbor.outputs.VERSION }} \
-          --tag minimalcompact/thumbor:latest \
-          thumbor/
-      - uses: actions/upload-artifact@v3
-        with:
-          name: images
-          path: /tmp/thumbor.tar
-  thumbor_simd:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        simd_level: ["sse4", "avx2"]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      - name: get thumbor version
-        id: thumbor
+          docker buildx build \
+            --progress plain \
+            --platform=$PLATFORM \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-thumbor \
+            --cache-to type=gha,scope=$GITHUB_REF_NAME-thumbor,mode=max,push=true \
+            --pull \
+            --target thumbor \
+            -f thumbor/Dockerfile \
+            thumbor/
+
+      - name: Build Thumbor w/ Pillow-SIMD images
         run: |
-          echo "VERSION=$(cat thumbor/requirements.txt| grep thumbor== | cut -d= -f 3)" >> $GITHUB_OUTPUT
-      - name: build image
-        ## TODO set platform to linux/amd64,linux/arm64 once supported
+          for SIMD_LEVEL in sse4 avx2; do
+            docker buildx build \
+              --progress plain \
+              --platform=$PLATFORM \
+              --cache-from type=gha,scope=$GITHUB_REF_NAME-thumbor-$SIMD_LEVEL \
+              --cache-to type=gha,scope=$GITHUB_REF_NAME-thumbor-$SIMD_LEVEL,mode=max,push=true \
+              --pull \
+              --build-arg SIMD_LEVEL=$SIMD_LEVEL \
+              --target pillow_simd \
+              -f thumbor/Dockerfile \
+              thumbor/
+          done
+
+      - name: Build Thumbor RemoteCV image
         run: |
-          docker buildx build --platform "linux/amd64" --build-arg SIMD_LEVEL=${{ matrix.simd_level }}  \
-          -o type=docker,dest=/tmp/thumbor_simd_${{ matrix.simd_level }}.tar \
-          -f thumbor/Dockerfile \
-          --tag minimalcompact/thumbor:${{ steps.thumbor.outputs.VERSION }}-simd-${{ matrix.simd_level }} \
-          --tag minimalcompact/thumbor:latest-simd-${{ matrix.simd_level }} \
-          thumbor/
-      - uses: actions/upload-artifact@v3
-        with:
-          name: images
-          path: /tmp/thumbor${{ matrix.simd_level}}.tar
-  remote_cv:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      - name: get thumbor version
-        id: thumbor
+          docker buildx build \
+            --progress plain \
+            --platform=$PLATFORM \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-remotecv \
+            --cache-to type=gha,scope=$GITHUB_REF_NAME-remotecv,mode=max,push=true \
+            --pull \
+            --target remotecv \
+            -f thumbor/Dockerfile \
+            thumbor/
+
+      - name: Build Nginx proxy cache image
         run: |
-          echo "VERSION=$(cat thumbor/requirements.txt| grep thumbor== | cut -d= -f 3)" >> $GITHUB_OUTPUT
-      - name: build image
+          docker buildx build \
+            --progress plain \
+            --platform=$PLATFORM \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-nginx-proxy \
+            --cache-to type=gha,scope=$GITHUB_REF_NAME-nginx-proxy,mode=max,push=true \
+            --pull \
+            -f nginx-proxy-cache/Dockerfile \
+            nginx-proxy-cache/
+
+      - name: Load Thumbor and Nginx proxy cache images into local Docker
         run: |
-          docker buildx build --platform=linux/amd64,linux/arm64 --build-arg THUMBOR_TAG=latest -f remotecv/Dockerfile \
-          -o type=docker,dest=/tmp/remote_cv.tar \
-          --tag  minimalcompact/remotecv:${{ steps.thumbor.outputs.VERSION }} \
-          --tag minimalcompact/remotecv:latest \
-          remotecv/
-      - uses: actions/upload-artifact@v3
-        with:
-          name: images
-          path: /tmp/remote_cv.tar
-  nginx_proxy_cache:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      - name: get thumbor version
-        id: thumbor
-        run: |
-          echo "VERSION=$(cat thumbor/requirements.txt| grep thumbor== | cut -d= -f 3)" >> $GITHUB_OUTPUT
-      - name: build image
-        ## TODO set platform to linux/amd64,linux/arm64 once supported
-        run: |
-          docker buildx build --platform=linux/amd64 --pull -f nginx-proxy-cache/Dockerfile \
-          -o type=docker,dest=/tmp/nginx_proxy_cache.tar \
-          --tag minimalcompact/thumbor-nginx-proxy-cache:${{ steps.thumbor.outputs.VERSION }} \
-          --tag minimalcompact/thumbor-nginx-proxy-cache:latest \
-          nginx-proxy-cache/
-      - uses: actions/upload-artifact@v3
-        with:
-          name: images
-          path: /tmp/nginx_proxy_cache.tar
-  test:
-    runs-on: ubuntu-latest
-    needs:
-      - thumbor
-      - nginx_proxy_cache
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: images
-          path: /tmp
-      - name: load images into docker
-        run: |
-          docker load --input /tmp/thumbor.tar
-          docker load --input /tmp/nginx_proxy_cache.tar
-          docker image ls -a
-      - name: install bats
+          
+          # Load image for current platform into local Docker (see https://github.com/docker/buildx/issues/59)
+          # To make --load work we have to omit the --platform argument
+          
+          docker buildx build \
+            --progress plain \
+            --target thumbor \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-thumbor \
+            --load \
+            --tag minimalcompact/thumbor \
+            -f thumbor/Dockerfile \
+            thumbor/
+
+          docker buildx build \
+            --progress plain \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-nginx-proxy \
+            --load \
+            --tag minimalcompact/thumbor-nginx-proxy-cache \
+            -f nginx-proxy-cache/Dockerfile \
+            nginx-proxy-cache/
+
+      - name: Install Bats
         run: |
           git clone https://github.com/bats-core/bats-core.git
           cd bats-core
           sudo ./install.sh /usr/local
-      - name: run bats tests
+
+      - name: Run tests with Bats
         run: |
           for filename in tests/*.bats; do sudo bats --tap "$filename" || exit 1; done
+
+      - uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Push images to ghcr.io registry
+        run: |
+
+          docker buildx build \
+            --progress plain \
+            --platform=$PLATFORM \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-thumbor \
+            --tag ghcr.io/MinimalCompact/thumbor:${{ steps.thumbor.outputs.VERSION }} \
+            --push \
+            --target thumbor \
+            -f thumbor/Dockerfile \
+            thumbor/
+
+          for SIMD_LEVEL in sse4 avx2; do
+            docker buildx build \
+              --progress plain \
+              --platform=$PLATFORM \
+              --cache-from type=gha,scope=$GITHUB_REF_NAME-thumbor-$SIMD_LEVEL \
+              --tag ghcr.io/MinimalCompact/thumbor:${{ steps.thumbor.outputs.VERSION }}-simd-$SIMD_LEVEL \
+              --push \
+              --build-arg SIMD_LEVEL=$SIMD_LEVEL \
+              --target pillow_simd \
+              -f thumbor/Dockerfile \
+              thumbor/
+          done
+
+          docker buildx build \
+            --progress plain \
+            --platform=$PLATFORM \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-remotecv \
+            --tag ghcr.io/MinimalCompact/thumbor:${{ steps.thumbor.outputs.VERSION }}-remotecv \
+            --push \
+            --target remotecv \
+            -f thumbor/Dockerfile \
+            thumbor/
+
+          docker buildx build \
+            --progress plain \
+            --platform=$PLATFORM \
+            --cache-from type=gha,scope=$GITHUB_REF_NAME-nginx-proxy \
+            --tag ghcr.io/MinimalCompact/thumbor:${{ steps.thumbor.outputs.VERSION }}-nginx-proxy-cache \
+            --push \
+            -f nginx-proxy-cache/Dockerfile \
+            nginx-proxy-cache/
